import api from "../../services/api";

const base = "/admin/ios";

export const iosApi = {
  access: () => api.get(`${base}/access`),
  workspace: () => api.get(`${base}/workspace`),
  bootstrap: () => api.post(`${base}/bootstrap`),
  updateWorkspace: (data) => api.patch(`${base}/workspace`, data),
  cockpit: () => api.get(`${base}/cockpit`),
  team: () => api.get(`${base}/team`),
  cycles: () => api.get(`${base}/cycles`),
  createCycle: (data) => api.post(`${base}/cycles`, data),
  updateCycle: (id, data) => api.patch(`${base}/cycles/${id}`, data),
  archiveCycle: (id) => api.delete(`${base}/cycles/${id}`),
  createObjective: (cycleId, data) => api.post(`${base}/cycles/${cycleId}/objectives`, data),
  updateObjective: (id, data) => api.patch(`${base}/objectives/${id}`, data),
  cancelObjective: (id) => api.delete(`${base}/objectives/${id}`),
  createKeyResult: (objectiveId, data) => api.post(`${base}/objectives/${objectiveId}/key-results`, data),
  updateKeyResult: (id, data) => api.patch(`${base}/key-results/${id}`, data),
  cancelKeyResult: (id) => api.delete(`${base}/key-results/${id}`),
  metrics: () => api.get(`${base}/metrics`),
  createMetric: (data) => api.post(`${base}/metrics`, data),
  updateMetric: (id, data) => api.patch(`${base}/metrics/${id}`, data),
  createObservation: (metricId, data) => api.post(`${base}/metrics/${metricId}/observations`, data),
  createInitiative: (cycleId, data) => api.post(`${base}/cycles/${cycleId}/initiatives`, data),
  updateInitiative: (id, data) => api.patch(`${base}/initiatives/${id}`, data),
  createMilestone: (initiativeId, data) => api.post(`${base}/initiatives/${initiativeId}/milestones`, data),
  updateMilestone: (id, data) => api.patch(`${base}/milestones/${id}`, data),
  linkTask: (initiativeId, taskId) => api.post(`${base}/initiatives/${initiativeId}/tasks`, { taskId }),
  unlinkTask: (initiativeId, taskId) => api.delete(`${base}/initiatives/${initiativeId}/tasks/${taskId}`),
  decisions: () => api.get(`${base}/decisions`),
  createDecision: (data) => api.post(`${base}/decisions`, data),
  updateDecision: (id, data) => api.patch(`${base}/decisions/${id}`, data),
  audit: (params) => api.get(`${base}/audit`, { params }),
  performance: (month) => api.get(`${base}/performance`, { params: month ? { month } : {} }),
  syncPerformance: (month) => api.post(`${base}/performance/sync`, { month }),
  scenarios: () => api.get(`${base}/scenarios`),
  createScenario: (data) => api.post(`${base}/scenarios`, data),
  updateScenario: (id, data) => api.patch(`${base}/scenarios/${id}`, data),
  runScenario: (id) => api.post(`${base}/scenarios/${id}/run`),
  publishScenario: (id) => api.post(`${base}/scenarios/${id}/publish`),
  versionScenario: (id) => api.post(`${base}/scenarios/${id}/versions`),
  commercial: () => api.get(`${base}/commercial`),
  createChannel: (data) => api.post(`${base}/commercial/channels`, data),
  updateChannel: (id, data) => api.patch(`${base}/commercial/channels/${id}`, data),
  createCampaign: (data) => api.post(`${base}/commercial/campaigns`, data),
  updateCampaign: (id, data) => api.patch(`${base}/commercial/campaigns/${id}`, data),
  createPartner: (data) => api.post(`${base}/commercial/partners`, data),
  updatePartner: (id, data) => api.patch(`${base}/commercial/partners/${id}`, data),
  createCommission: (data) => api.post(`${base}/commercial/commissions`, data),
  updateCommission: (id, data) => api.patch(`${base}/commercial/commissions/${id}`, data),
  product: () => api.get(`${base}/product`),
  createRelease: (data) => api.post(`${base}/product/releases`, data),
  updateRelease: (id, data) => api.patch(`${base}/product/releases/${id}`, data),
  linkReleaseTask: (id, taskId) => api.post(`${base}/product/releases/${id}/tasks`, { taskId }),
  unlinkReleaseTask: (id, taskId) => api.delete(`${base}/product/releases/${id}/tasks/${taskId}`),
  createAdoption: (data) => api.post(`${base}/product/adoption`, data),
  people: () => api.get(`${base}/people`),
  createPosition: (data) => api.post(`${base}/people/positions`, data),
  updatePosition: (id, data) => api.patch(`${base}/people/positions/${id}`, data),
};

export function iosError(error, fallback = "Não foi possível concluir a ação.") {
  return error?.response?.data?.error || fallback;
}
